"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.app = void 0;
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const cookie_parser_1 = __importDefault(require("cookie-parser"));
const helmet_1 = __importDefault(require("helmet"));
const env_1 = require("./config/env");
const error_handler_1 = require("./middleware/error-handler");
const admin_routes_1 = require("./modules/admin/admin.routes");
const auth_routes_1 = require("./modules/auth/auth.routes");
exports.app = (0, express_1.default)();
exports.app.disable("x-powered-by");
exports.app.use((0, helmet_1.default)());
exports.app.use((0, cors_1.default)({ origin: env_1.env.CORS_ORIGIN, credentials: true }));
exports.app.use(express_1.default.json({ limit: "16kb" }));
exports.app.use((0, cookie_parser_1.default)());
exports.app.get("/health", (_request, response) => response.json({ status: "ok" }));
exports.app.use("/api/auth", auth_routes_1.authRouter);
exports.app.use("/api/admin", admin_routes_1.adminRouter);
exports.app.use(error_handler_1.notFoundHandler);
exports.app.use(error_handler_1.errorHandler);
